version: 2.0.{build}
os: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
    
before_build:
- cmd: dotnet --version

build_script:
# Cake.
- ps: .\build.ps1

after_build:
- cmd: buildNuget.cmd

# Tests are executed by Cake.
test: off

artifacts:
  - path: .\src\nuget\*.nupkg
    name: Libraries NuGet packages